import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import JSZip from "jszip";
import { NextResponse } from "next/server";
import { activeProjectId, safeProjectPath } from "@/server/paths";
import { validatePresentationExport } from "@/server/presentation-validation";
import { generatePptx } from "@/server/slides";
import { loadProject } from "@/server/store";

export const runtime = "nodejs";

export async function GET(request: Request, { params }: { params: Promise<{ type: string }> }) {
  const { type } = await params;
  const project = await loadProject(activeProjectId(request));
  if (type === "pptx") {
    const buffer = await generatePptx(project);
    const validationRoot = await safeProjectPath(project.id, "reviews", "presentation");
    await mkdir(validationRoot, { recursive: true });
    const evidenceDirectory = await mkdtemp(path.join(validationRoot, "export-"));
    const validation = await validatePresentationExport(buffer, { outputDir: evidenceDirectory, render: true });
    await writeFile(path.join(evidenceDirectory, "report.json"), `${JSON.stringify(validation, null, 2)}\n`, "utf8");
    await writeFile(path.join(validationRoot, "latest.json"), `${JSON.stringify(validation, null, 2)}\n`, "utf8");
    return new NextResponse(new Uint8Array(buffer), { headers: {
      "content-type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      "content-disposition": `attachment; filename="${project.brand.name.toLowerCase()}-launch-deck.pptx"`,
      "x-codex-validation-mode": validation.capability.mode,
      "x-codex-rendered": String(validation.rendered)
    } });
  }
  if (type === "tokens") {
    return NextResponse.json(project.tokens, { headers: { "content-disposition": `attachment; filename="${project.brand.name.toLowerCase()}-design-system.json"` } });
  }
  if (type === "web") {
    const zip = new JSZip();
    zip.file("index.html", await readFile(await safeProjectPath(project.id, "web", "index.html")));
    zip.file("design-system/tokens.json", await readFile(await safeProjectPath(project.id, "design-system", "tokens.json")));
    zip.file("design-system/tokens.css", await readFile(await safeProjectPath(project.id, "design-system", "tokens.css")));
    zip.file("README.txt", `Generated by Codex Design Studio\nBrand: ${project.brand.name}\nTokens version: ${project.tokens.version}\nOpen index.html in a modern browser.\n`);
    const buffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
    return new NextResponse(new Uint8Array(buffer), { headers: { "content-type": "application/zip", "content-disposition": `attachment; filename="${project.brand.name.toLowerCase()}-landing.zip"` } });
  }
  return NextResponse.json({ error: "Unknown export type." }, { status: 404 });
}
