import { readFile } from "node:fs/promises";
import JSZip from "jszip";
import { NextResponse } from "next/server";
import { activeProjectId, safeProjectPath } from "@/server/paths";
import { generatePptx } from "@/server/slides";
import { loadProject } from "@/server/store";

export const runtime = "nodejs";

export async function GET(request: Request, { params }: { params: Promise<{ type: string }> }) {
  const { type } = await params;
  const project = await loadProject(activeProjectId(request));
  if (type === "pptx") {
    const buffer = await generatePptx(project);
    return new NextResponse(new Uint8Array(buffer), { headers: { "content-type": "application/vnd.openxmlformats-officedocument.presentationml.presentation", "content-disposition": `attachment; filename="${project.brand.name.toLowerCase()}-launch-deck.pptx"` } });
  }
  if (type === "tokens") {
    return NextResponse.json(project.tokens, { headers: { "content-disposition": `attachment; filename="${project.brand.name.toLowerCase()}-design-system.json"` } });
  }
  if (type === "web") {
    const zip = new JSZip();
    zip.file("index.html", await readFile(await safeProjectPath(project.id, "web", "index.html")));
    zip.file("design-system/tokens.json", await readFile(await safeProjectPath(project.id, "design-system", "tokens.json")));
    zip.file("design-system/tokens.css", await readFile(await safeProjectPath(project.id, "design-system", "tokens.css")));
    zip.file("README.txt", `Generated by Codex Design Studio\nBrand: ${project.brand.name}\nTokens version: ${project.tokens.version}\nOpen index.html in a modern browser.\n`);
    const buffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
    return new NextResponse(new Uint8Array(buffer), { headers: { "content-type": "application/zip", "content-disposition": `attachment; filename="${project.brand.name.toLowerCase()}-landing.zip"` } });
  }
  return NextResponse.json({ error: "Unknown export type." }, { status: 404 });
}
